export const blogData = [
  {
    userId: 1,
    id: 1,
    user: "Jharna Saha",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    designation: "Head of Marketing",
    date: "25th April 2022",
    title: "How to Keep Your Appliances in Good Health with Smi-Fi",
    body: "The Hidden Costs of Neglecting Appliance Health and How Smi-Fi Can Help",
  },
  {
    userId: 1,
    id: 2,
    user: "Demi WIlkinson",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    designation: "Software Engineering",
    date: "20 Jan 2022",
    title: "qui est esse",

    body: "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla",
  },
  {
    userId: 1,
    id: 3,
    user: "Demi WIlkinson",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    date: "20 Jan 2022",
    designation: "Software Engineering",
    title: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    body: "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut",
  },
  {
    userId: 1,
    id: 4,
    user: "Demi WIlkinson",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    date: "20 Jan 2022",
    designation: "Software Engineering",
    title: "eum et est occaecati",
    body: "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit",
  },
  {
    userId: 1,
    id: 5,
    user: "Demi WIlkinson",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    date: "20 Jan 2022",
    designation: "Software Engineering",
    title: "nesciunt quas odio",
    body: "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque",
  },
  {
    userId: 1,
    id: 6,
    user: "Demi WIlkinson",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    designation: "Software Engineering",
    date: "20 Jan 2022",
    title: "dolorem eum magni eos aperiam quia",
    body: "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae",
  },
  {
    userId: 1,
    id: 7,
    user: "Demi WIlkinson",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    date: "20 Jan 2022",
    designation: "Software Engineering",
    title: "magnam facilis autem",
    body: "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas",
  },
  {
    userId: 1,
    id: 8,
    user: "Demi WIlkinson",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    date: "20 Jan 2022",
    designation: "Software Engineering",
    title: "dolorem dolore est ipsam",
    body: "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae",
  },
  {
    userId: 1,
    id: 9,
    user: "Demi WIlkinson",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    date: "20 Jan 2022",
    designation: "Software Engineering",
    title: "nesciunt iure omnis dolorem tempora et accusantium",
    body: "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas",
  },
  {
    userId: 1,
    id: 10,
    user: "Demi WIlkinson",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    date: "20 Jan 2022",
    designation: "Software Engineering",
    title: "optio molestias id quia eum",
    body: "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error",
  },
  {
    userId: 2,
    id: 11,
    user: "Demi WIlkinson",
    linkedIn: "https://www.linkedin.com/in/jharna-saha/",
    date: "20 Jan 2022",
    designation: "Software Engineering",
    title: "et ea vero quia laudantium autem",
    body: "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi",
  },
];
